/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v11.0
processor: LPC54S018
package_id: LPC54S018JET180
mcu_data: ksdk2_0
processor_version: 12.0.0
board: LPCXpresso54S018
functionalGroups:
- name: INIT_Peripherals
  UUID: 743d174d-6f82-4cdc-abec-91cd08bb8d17
  selectedCore: core0
- name: INIT_Peripherals_DEBBUG
  UUID: 743d174d-6f82-4cdc-abec-91cd08bb8d17
  selectedCore: core0
- name: INIT_Peripherals_PMBus
  UUID: 743d174d-6f82-4cdc-abec-91cd08bb8d17
  selectedCore: core0
- name: INIT_Periphals_Ethernet
  UUID: 25410ed5-74b7-42c6-8ab3-462ee77818e6
  selectedCore: core0
- name: INIT_Peripherals_TImer
  UUID: 077f5411-e853-4699-a5fd-59e81c42d8e3
  selectedCore: core0
- name: INIT_Peripherals_I2C_RTOS
  UUID: 4a828edb-dd42-4023-b6bb-aed9e7c8c681
  selectedCore: core0
- name: INIT_Peripherals_I2C
  UUID: 4a828edb-dd42-4023-b6bb-aed9e7c8c681
  selectedCore: core0
- name: INIT_Peripherals_I2C_HS
  UUID: 4a828edb-dd42-4023-b6bb-aed9e7c8c681
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * INIT_Peripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'INIT_Peripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * SMBus_PCIe1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SMBus_PCIe1'
- type: 'flexcomm_i2c'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals'
- peripheral: 'FLEXCOMM2'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '100000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM2_IRQn'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t SMBus_PCIe1_rtosHandle;
const i2c_master_config_t SMBus_PCIe1_config = {
  .enableMaster = true,
  .baudRate_Bps = 100000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};

static void SMBus_PCIe1_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&SMBus_PCIe1_rtosHandle, SMBUS_PCIE1_PERIPHERAL, &SMBus_PCIe1_config, SMBUS_PCIE1_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * SMBus_PCIe2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SMBus_PCIe2'
- type: 'flexcomm_i2c'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals'
- peripheral: 'FLEXCOMM1'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '100000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM1_IRQn'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t SMBus_PCIe2_rtosHandle;
const i2c_master_config_t SMBus_PCIe2_config = {
  .enableMaster = true,
  .baudRate_Bps = 100000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};

static void SMBus_PCIe2_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&SMBus_PCIe2_rtosHandle, SMBUS_PCIE2_PERIPHERAL, &SMBus_PCIe2_config, SMBUS_PCIE2_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * INIT_Peripherals_DEBBUG functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC_2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC_2'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'INIT_Peripherals_DEBBUG'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_2_init(void) {
} */

/***********************************************************************************************************************
 * DebugConsole initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DebugConsole'
- type: 'debug_console'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'debug_console_51864e4f3ac859dae7b603e07bc4ae33'
- functional_group: 'INIT_Peripherals_DEBBUG'
- config_sets:
  - fsl_debug_console:
    - config:
      - SDK_DEBUGCONSOLE: 'DEBUGCONSOLE_REDIRECT_TO_SDK'
      - SDK_DEBUGCONSOLE_UART: 'serial_port'
      - DEBUG_CONSOLE_RX_ENABLE: 'true'
      - DEBUG_CONSOLE_PRINTF_MAX_LOG_LEN: '128'
      - DEBUG_CONSOLE_SCANF_MAX_LOG_LEN: '20'
      - DEBUG_CONSOLE_ENABLE_ECHO: 'false'
      - PRINTF_FLOAT_ENABLE: 'false'
      - SCANF_FLOAT_ENABLE: 'false'
      - PRINTF_ADVANCED_ENABLE: 'false'
      - SCANF_ADVANCED_ENABLE: 'false'
      - DEBUG_CONSOLE_TRANSFER_NON_BLOCKING: 'false'
      - DEBUG_CONSOLE_TRANSMIT_BUFFER_LEN: '512'
      - DEBUG_CONSOLE_RECEIVE_BUFFER_LEN: '1024'
      - DEBUG_CONSOLE_TX_RELIABLE_ENABLE: 'true'
      - DEBUG_CONSOLE_DISABLE_RTOS_SYNCHRONIZATION: 'false'
    - peripheral_config:
      - serial_port_type: 'kSerialPort_Uart'
      - uart_config:
        - peripheralUART: 'FLEXCOMM0'
        - clockSource: 'genericUartClockSource'
        - clockSourceFreq: 'BOARD_BootClockPLL180M'
        - baudRate_Bps: '115200'
        - quick_selection: 'QuickSelection1'
    - debug_console_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void DebugConsole_init(void) {
  /* Debug console initialization */
  DbgConsole_Init(DEBUGCONSOLE_INSTANCE, DEBUGCONSOLE_BAUDRATE, DEBUGCONSOLE_TYPE, DEBUGCONSOLE_CLK_FREQ);
}

/***********************************************************************************************************************
 * INIT_Peripherals_PMBus functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC_3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC_3'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'INIT_Peripherals_PMBus'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_3_init(void) {
} */

/***********************************************************************************************************************
 * INIT_Periphals_Ethernet functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * MPU initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MPU'
- type: 'mpu_utility'
- mode: 'MPU'
- custom_name_enabled: 'false'
- type_id: 'mpu_utility_bc3ea1f6add76edb6050f698d423d163'
- functional_group: 'INIT_Periphals_Ethernet'
- peripheral: 'MPU'
- config_sets:
  - mpu_init:
    - mpuInit: 'disabled'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void MPU_init(void) {
} */

/***********************************************************************************************************************
 * NVIC_4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC_4'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'INIT_Periphals_Ethernet'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_4_init(void) {
} */

/***********************************************************************************************************************
 * lwIP initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'lwIP'
- type: 'lwip'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lwip_e916e23135ce42147b8e9c16b7728f8a'
- functional_group: 'INIT_Periphals_Ethernet'
- config_sets:
  - lwip_config:
    - mode: 'freertos'
    - LWIP_NETIF_API: 'true'
    - LWIP_NETCONN: 'true'
    - LWIP_SOCKET: 'true'
    - LWIP_SO_RCVTIMEO: 'true'
    - LWIP_TCPIP_CORE_LOCKING: 'true'
    - MEM_SIZE: '(22 * 1024)'
    - MEMP_NUM_PBUF: '15'
    - MEMP_NUM_UDP_PCB: '6'
    - MEMP_NUM_TCP_PCB: '10'
    - MEMP_NUM_TCP_PCB_LISTEN: '6'
    - MEMP_NUM_TCP_SEG: '22'
    - MEMP_NUM_SYS_TIMEOUT: '10'
    - PBUF_POOL_SIZE: '5'
    - LWIP_SINGLE_NETIF: 'true'
    - LWIP_IPV4: 'true'
    - IP_FORWARD: 'false'
    - IP_REASSEMBLY: 'true'
    - IP_FRAG: 'true'
    - IP_DEFAULT_TTL: '255'
    - LWIP_ARP: 'true'
    - LWIP_ICMP: 'true'
    - ICMP_TTL: 'IP_DEFAULT_TTL'
    - LWIP_BROADCAST_PING: 'false'
    - LWIP_MULTICAST_PING: 'false'
    - LWIP_IGMP: 'false'
    - LWIP_DHCP: 'true'
    - LWIP_DHCP_DOES_ACD_CHECK: 'true'
    - LWIP_IPV6: 'false'
    - LWIP_IPV6_NUM_ADDRESSES: '3'
    - LWIP_IPV6_AUTOCONFIG: 'true'
    - LWIP_IPV6_DHCP6: 'false'
    - LWIP_RAW: 'false'
    - RAW_TTL: 'IP_DEFAULT_TTL'
    - LWIP_TCP: 'true'
    - TCP_TTL: 'IP_DEFAULT_TTL'
    - TCP_QUEUE_OOSEQ: 'false'
    - TCP_MSS: '(1500 - 40)'
    - TCP_SND_BUF: '(6 * TCP_MSS)'
    - TCP_SND_QUEUELEN: '(3 * TCP_SND_BUF) / TCP_MSS'
    - TCP_WND: '(2 * TCP_MSS)'
    - TCP_LISTEN_BACKLOG: 'true'
    - TCP_DEFAULT_LISTEN_BACKLOG: '0xFF'
    - LWIP_UDP: 'true'
    - UDP_TTL: 'IP_DEFAULT_TTL'
    - LWIP_STATS: 'false'
    - LWIP_PROVIDE_ERRNO: 'true'
    - CHECKSUM_BY_HARDWARE: 'false'
    - LWIP_DEBUG: 'true'
    - DEFAULT_THREAD_STACKSIZE: '3000'
    - DEFAULT_THREAD_PRIO: '3'
    - TCPIP_MBOX_SIZE: '32'
    - TCPIP_THREAD_STACKSIZE: '1024'
    - TCPIP_THREAD_PRIO: '8'
    - DEFAULT_UDP_RECVMBOX_SIZE: '12'
    - DEFAULT_TCP_RECVMBOX_SIZE: '12'
    - DEFAULT_ACCEPTMBOX_SIZE: '12'
    - custom_opts: ''
    - modules_include: ''
    - mpu_init:
      - mpu_init_component: 'MPU'
    - user_preinit: 'true'
    - user_init:
      - initFunctionID: 'lwIP_interface_init'
    - lwip_init: 'true'
    - enableCallback: 'true'
    - initFnCallback:
      - callbackFunction: 'tcpip_init_done'
      - arg_ptr: ''
    - ifConfig:
      - 0:
        - ethernetif_config_struct: []
        - phy_handle_struct: []
        - mdio_handle_struct: []
        - mdio_resource_struct: []
        - netif_id: 'netif0'
        - interface: 'enet'
        - netif_mode: 'ipv4'
        - ip_assignment: 'dynamic'
        - ipv4Config:
          - ip_addr:
            - addr: '0.0.0.0'
          - netmask:
            - addr: '255.255.255.0'
          - gateway:
            - addr: '0.0.0.0'
        - netif_function_name: 'defaultFn'
        - netif_input_function_name: 'defaultInputFn'
        - mac_address:
          - useSiliconId: 'true'
          - addr: 'FF-FF-FF-FF-FF-FF'
        - phyConfig:
          - phy_driver: 'phylan8720a'
          - phy_addr: '0x0'
          - mdioConfig:
            - enetConfig:
              - peripheralSelect: 'ENET'
              - timing:
                - globalClockConfig:
                  - clockSource: 'GlobalClock'
                  - clockSourceFreq: 'BOARD_BootClockPLL180M'
              - lpc_enet_config:
                - phyTiming:
                  - refClockConfig:
                    - clockSource: 'EnetRefClock'
                    - clockSourceFreq: 'custom:50 MHz'
              - quick_selection: 'QuickSelection1'
    - lwip_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* IPv4 adress, netmask and gateway handle */
ip4_addr_t lwIP_netif0_ipaddr, lwIP_netif0_netmask, lwIP_netif0_gw;
/* Network interface structure */
struct netif lwIP_netif0;
static mdio_handle_t lwIP_netif0_mdio_handle = {
  .resource = LWIP_NETIF0_MDIO_RESOURCE,
  .ops = &LWIP_NETIF0_MDIO_OPS
};
static phy_handle_t lwIP_netif0_phy_handle = {
  .phyAddr = LWIP_NETIF0_PHY_ADDRESS,
  .mdioHandle = &lwIP_netif0_mdio_handle,
  .ops = &LWIP_NETIF0_PHY_OPS
};
ethernetif_config_t lwIP_netif0_enet_config = {
  .phyHandle = &lwIP_netif0_phy_handle,
#ifdef LWIP_NETIF0_MAC_ADDRESS
  .macAddress = LWIP_NETIF0_MAC_ADDRESS,
#endif
};

static void lwIP_init(void) {
  /* lwIP user physical abstraction initialization */
  lwIP_interface_init();
  /* lwIP IP address initialization */
  IP4_ADDR(&lwIP_netif0_ipaddr, LWIP_NETIF0_IPADDR0, LWIP_NETIF0_IPADDR1, LWIP_NETIF0_IPADDR2, LWIP_NETIF0_IPADDR3);
  /* lwIP netmask initialization */
  IP4_ADDR(&lwIP_netif0_netmask, LWIP_NETIF0_NETMASK0, LWIP_NETIF0_NETMASK1, LWIP_NETIF0_NETMASK2, LWIP_NETIF0_NETMASK3);
  /* lwIP gateway initialization */
  IP4_ADDR(&lwIP_netif0_gw, LWIP_NETIF0_GW0, LWIP_NETIF0_GW1, LWIP_NETIF0_GW2, LWIP_NETIF0_GW3);
  /* lwIP module initialization */
  tcpip_init(tcpip_init_done, NULL);
#ifndef LWIP_NETIF0_MAC_ADDRESS
  /* Set special address for each chip. */
  (void)SILICONID_ConvertToMacAddr(&lwIP_netif0_enet_config.macAddress);
#endif
  /* lwIP network interface initialization */
  netifapi_netif_add(&lwIP_netif0, &lwIP_netif0_ipaddr, &lwIP_netif0_netmask, &lwIP_netif0_gw, &lwIP_netif0_enet_config, ethernetif0_init, tcpip_input);
  netifapi_netif_set_default(&lwIP_netif0);
  netifapi_netif_set_up(&lwIP_netif0);
  /* lwIP DHCP initialization */
  netifapi_dhcp_start(&lwIP_netif0);
}

/***********************************************************************************************************************
 * INIT_Peripherals_TImer functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC_5 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC_5'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'INIT_Peripherals_TImer'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_5_init(void) {
} */

/***********************************************************************************************************************
 * RIT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'RIT'
- type: 'rit'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'rit_b722f95e53018d6f73a2b67d43c4ab32'
- functional_group: 'INIT_Peripherals_TImer'
- peripheral: 'RIT'
- config_sets:
  - general:
    - timingConfig:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockFROHF96M'
    - enableRunInDebug: 'false'
    - resetOnMatch: 'true'
    - compareValue: '1 Hz'
    - startTimer: 'false'
    - enableInterrupt: 'true'
    - interrupt:
      - IRQn: 'RIT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'true'
      - priority: '3'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const rit_config_t RIT_config = {
  .enableRunInDebug = false
};

static void RIT_init(void) {
  /* Initialize the RIT */
  RIT_Init(RIT_PERIPHERAL, &RIT_config);
  /* Interrupt vector RIT_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(RIT_IRQN, RIT_IRQ_PRIORITY);
  /* Enable interrupt RIT_IRQn request in the NVIC. */
  EnableIRQ(RIT_IRQN);
  /* Set the register reset to zero when the counter value equals the set period. */
  RIT_SetCountAutoClear(RIT_PERIPHERAL, true);
  /* Set the compare register value. */
  RIT_SetTimerCompare(RIT_PERIPHERAL, RIT_TICKS);
}

/***********************************************************************************************************************
 * INIT_Peripherals_I2C_RTOS functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC_6 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC_6'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'INIT_Peripherals_I2C_RTOS'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_6_init(void) {
} */

/***********************************************************************************************************************
 * I2C_PCIE1_RTOS initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_PCIE1_RTOS'
- type: 'flexcomm_i2c'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals_I2C_RTOS'
- peripheral: 'FLEXCOMM6'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '100000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM6_IRQn'
      - enable_priority: 'false'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t I2C_PCIE1_RTOS_rtosHandle;
const i2c_master_config_t I2C_PCIE1_RTOS_config = {
  .enableMaster = true,
  .baudRate_Bps = 100000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};

static void I2C_PCIE1_RTOS_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&I2C_PCIE1_RTOS_rtosHandle, I2C_PCIE1_RTOS_PERIPHERAL, &I2C_PCIE1_RTOS_config, I2C_PCIE1_RTOS_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * I2C_PCIE2_RTOS initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_PCIE2_RTOS'
- type: 'flexcomm_i2c'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals_I2C_RTOS'
- peripheral: 'FLEXCOMM9'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '1000000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM9_IRQn'
      - enable_priority: 'false'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t I2C_PCIE2_RTOS_rtosHandle;
const i2c_master_config_t I2C_PCIE2_RTOS_config = {
  .enableMaster = true,
  .baudRate_Bps = 1000000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};

static void I2C_PCIE2_RTOS_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&I2C_PCIE2_RTOS_rtosHandle, I2C_PCIE2_RTOS_PERIPHERAL, &I2C_PCIE2_RTOS_config, I2C_PCIE2_RTOS_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * I2C_SUPP_RTOS initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_SUPP_RTOS'
- type: 'flexcomm_i2c'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals_I2C_RTOS'
- peripheral: 'FLEXCOMM8'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '1000000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM8_IRQn'
      - enable_priority: 'false'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t I2C_SUPP_RTOS_rtosHandle;
const i2c_master_config_t I2C_SUPP_RTOS_config = {
  .enableMaster = true,
  .baudRate_Bps = 1000000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};

static void I2C_SUPP_RTOS_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&I2C_SUPP_RTOS_rtosHandle, I2C_SUPP_RTOS_PERIPHERAL, &I2C_SUPP_RTOS_config, I2C_SUPP_RTOS_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * INIT_Peripherals_I2C functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC_7 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC_7'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'INIT_Peripherals_I2C'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_7_init(void) {
} */

/***********************************************************************************************************************
 * I2C_PCIE1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_PCIE1'
- type: 'flexcomm_i2c'
- mode: 'I2C_Transfer'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals_I2C'
- peripheral: 'FLEXCOMM6'
- config_sets:
  - transferCfg:
    - transfer:
      - init_callback: 'true'
      - callback_fcn: 'I2C_PCIE1_clb'
      - user_data: ''
      - init_transfer: 'true'
      - master_transfer_cfg:
        - flags: 'kI2C_TransferDefaultFlag'
        - slaveAddress: '0'
        - direction: 'kI2C_Write'
        - subaddressSize: '1'
        - subaddress: '0'
        - dataSize: '2'
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '1000000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM6_IRQn'
      - enable_priority: 'false'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_master_config_t I2C_PCIE1_config = {
  .enableMaster = true,
  .baudRate_Bps = 1000000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};
i2c_master_handle_t I2C_PCIE1_handle;
uint8_t I2C_PCIE1_buffer[I2C_PCIE1_BUFFER_SIZE];
i2c_master_transfer_t I2C_PCIE1_transfer;

static void I2C_PCIE1_init(void) {
  /* Initialization function */
  I2C_MasterInit(I2C_PCIE1_PERIPHERAL, &I2C_PCIE1_config, I2C_PCIE1_CLOCK_SOURCE);
  memset(&I2C_PCIE1_handle, 0, sizeof(I2C_PCIE1_handle));
  memset(&I2C_PCIE1_transfer, 0, sizeof(I2C_PCIE1_transfer));

  I2C_PCIE1_transfer.slaveAddress = 0;
  I2C_PCIE1_transfer.direction = kI2C_Write;
  I2C_PCIE1_transfer.subaddress = (uint32_t)NULL;
  I2C_PCIE1_transfer.subaddressSize = 1;
  I2C_PCIE1_transfer.data = I2C_PCIE1_buffer;
  I2C_PCIE1_transfer.dataSize = I2C_PCIE1_BUFFER_SIZE;
  I2C_PCIE1_transfer.flags = kI2C_TransferDefaultFlag;
  I2C_MasterTransferCreateHandle(I2C_PCIE1_PERIPHERAL, &I2C_PCIE1_handle, I2C_PCIE1_clb, NULL);
}

/***********************************************************************************************************************
 * I2C_PCIE2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_PCIE2'
- type: 'flexcomm_i2c'
- mode: 'I2C_Transfer'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals_I2C'
- peripheral: 'FLEXCOMM9'
- config_sets:
  - transferCfg:
    - transfer:
      - init_callback: 'true'
      - callback_fcn: 'I2C_PCIE2_clb'
      - user_data: ''
      - init_transfer: 'true'
      - master_transfer_cfg:
        - flags: 'kI2C_TransferDefaultFlag'
        - slaveAddress: '0'
        - direction: 'kI2C_Write'
        - subaddressSize: '1'
        - subaddress: '0'
        - dataSize: '2'
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '1000000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM9_IRQn'
      - enable_priority: 'false'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_master_config_t I2C_PCIE2_config = {
  .enableMaster = true,
  .baudRate_Bps = 1000000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};
i2c_master_handle_t I2C_PCIE2_handle;
uint8_t I2C_PCIE2_buffer[I2C_PCIE2_BUFFER_SIZE];
i2c_master_transfer_t I2C_PCIE2_transfer;

static void I2C_PCIE2_init(void) {
  /* Initialization function */
  I2C_MasterInit(I2C_PCIE2_PERIPHERAL, &I2C_PCIE2_config, I2C_PCIE2_CLOCK_SOURCE);
  memset(&I2C_PCIE2_handle, 0, sizeof(I2C_PCIE2_handle));
  memset(&I2C_PCIE2_transfer, 0, sizeof(I2C_PCIE2_transfer));

  I2C_PCIE2_transfer.slaveAddress = 0;
  I2C_PCIE2_transfer.direction = kI2C_Write;
  I2C_PCIE2_transfer.subaddress = (uint32_t)NULL;
  I2C_PCIE2_transfer.subaddressSize = 1;
  I2C_PCIE2_transfer.data = I2C_PCIE2_buffer;
  I2C_PCIE2_transfer.dataSize = I2C_PCIE2_BUFFER_SIZE;
  I2C_PCIE2_transfer.flags = kI2C_TransferDefaultFlag;
  I2C_MasterTransferCreateHandle(I2C_PCIE2_PERIPHERAL, &I2C_PCIE2_handle, I2C_PCIE2_clb, NULL);
}

/***********************************************************************************************************************
 * I2C_SUPP initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_SUPP'
- type: 'flexcomm_i2c'
- mode: 'I2C_Transfer'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals_I2C'
- peripheral: 'FLEXCOMM8'
- config_sets:
  - transferCfg:
    - transfer:
      - init_callback: 'true'
      - callback_fcn: 'I2C_SUPP_clb'
      - user_data: ''
      - init_transfer: 'true'
      - master_transfer_cfg:
        - flags: 'kI2C_TransferDefaultFlag'
        - slaveAddress: '0'
        - direction: 'kI2C_Write'
        - subaddressSize: '1'
        - subaddress: '0'
        - dataSize: '2'
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '1000000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM8_IRQn'
      - enable_priority: 'false'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_master_config_t I2C_SUPP_config = {
  .enableMaster = true,
  .baudRate_Bps = 1000000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};
i2c_master_handle_t I2C_SUPP_handle;
uint8_t I2C_SUPP_buffer[I2C_SUPP_BUFFER_SIZE];
i2c_master_transfer_t I2C_SUPP_transfer;

static void I2C_SUPP_init(void) {
  /* Initialization function */
  I2C_MasterInit(I2C_SUPP_PERIPHERAL, &I2C_SUPP_config, I2C_SUPP_CLOCK_SOURCE);
  memset(&I2C_SUPP_handle, 0, sizeof(I2C_SUPP_handle));
  memset(&I2C_SUPP_transfer, 0, sizeof(I2C_SUPP_transfer));

  I2C_SUPP_transfer.slaveAddress = 0;
  I2C_SUPP_transfer.direction = kI2C_Write;
  I2C_SUPP_transfer.subaddress = (uint32_t)NULL;
  I2C_SUPP_transfer.subaddressSize = 1;
  I2C_SUPP_transfer.data = I2C_SUPP_buffer;
  I2C_SUPP_transfer.dataSize = I2C_SUPP_BUFFER_SIZE;
  I2C_SUPP_transfer.flags = kI2C_TransferDefaultFlag;
  I2C_MasterTransferCreateHandle(I2C_SUPP_PERIPHERAL, &I2C_SUPP_handle, I2C_SUPP_clb, NULL);
}

/***********************************************************************************************************************
 * INIT_Peripherals_I2C_HS functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * I2C_PCIE1_RTOS_HS initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_PCIE1_RTOS_HS'
- type: 'flexcomm_i2c'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals_I2C_HS'
- peripheral: 'FLEXCOMM2'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '1000000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM2_IRQn'
      - enable_priority: 'false'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t I2C_PCIE1_RTOS_HS_rtosHandle;
const i2c_master_config_t I2C_PCIE1_RTOS_HS_config = {
  .enableMaster = true,
  .baudRate_Bps = 1000000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};

static void I2C_PCIE1_RTOS_HS_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&I2C_PCIE1_RTOS_HS_rtosHandle, I2C_PCIE1_RTOS_HS_PERIPHERAL, &I2C_PCIE1_RTOS_HS_config, I2C_PCIE1_RTOS_HS_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * I2C_PCIE2_RTOS_HS initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_PCIE2_RTOS_HS'
- type: 'flexcomm_i2c'
- mode: 'freertos'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_c8597948f61bd571ab263ea4330b9dd6'
- functional_group: 'INIT_Peripherals_I2C_HS'
- peripheral: 'FLEXCOMM1'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockPLL180M'
    - rtos_handle:
      - enable_custom_name: 'false'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '1000000'
      - enableTimeout: 'false'
      - timeout_Ms: '35'
    - interrupt_priority:
      - IRQn: 'FLEXCOMM1_IRQn'
      - enable_priority: 'false'
      - priority: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
i2c_rtos_handle_t I2C_PCIE2_RTOS_HS_rtosHandle;
const i2c_master_config_t I2C_PCIE2_RTOS_HS_config = {
  .enableMaster = true,
  .baudRate_Bps = 1000000UL,
  .enableTimeout = false,
  .timeout_Ms = 35U
};

static void I2C_PCIE2_RTOS_HS_init(void) {
  /* Initialization function */
  I2C_RTOS_Init(&I2C_PCIE2_RTOS_HS_rtosHandle, I2C_PCIE2_RTOS_HS_PERIPHERAL, &I2C_PCIE2_RTOS_HS_config, I2C_PCIE2_RTOS_HS_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * NVIC_8 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC_8'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'INIT_Peripherals_I2C_HS'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_8_init(void) {
} */

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void INIT_Peripherals(void)
{
  /* Initialize components */
  SMBus_PCIe1_init();
  SMBus_PCIe2_init();
}

void INIT_Peripherals_DEBBUG(void)
{
  /* Initialize components */
  DebugConsole_init();
}

void INIT_Peripherals_PMBus(void)
{
  /* Initialize components */
}

void INIT_Periphals_Ethernet(void)
{
  /* Global initialization */
  ARM_MPU_Disable();

  /* Initialize components */
  lwIP_init();
}

void INIT_Peripherals_TImer(void)
{
  /* Initialize components */
  RIT_init();
}

void INIT_Peripherals_I2C_RTOS(void)
{
  /* Initialize components */
  I2C_PCIE1_RTOS_init();
  I2C_PCIE2_RTOS_init();
  I2C_SUPP_RTOS_init();
}

void INIT_Peripherals_I2C(void)
{
  /* Initialize components */
  I2C_PCIE1_init();
  I2C_PCIE2_init();
  I2C_SUPP_init();
}

void INIT_Peripherals_I2C_HS(void)
{
  /* Initialize components */
  I2C_PCIE1_RTOS_HS_init();
  I2C_PCIE2_RTOS_HS_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
}
