/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/* Define the PIO[ANAMODE] bit macro (SDK 2.6.x and older miss this bit macro definition) */
#ifndef IOCON_PIO_ANAMODE_MASK
#define IOCON_PIO_ANAMODE_MASK  (0x40U)
#define IOCON_PIO_ANAMODE_SHIFT (6U)
#define IOCON_PIO_ANAMODE(x)    (((uint32_t)(((uint32_t)(x)) << IOCON_PIO_ANAMODE_SHIFT)) & IOCON_PIO_ANAMODE_MASK)
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_ANAMODE_DI 0x40u    /*!<@brief Disable analog Mode */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_FUNC2 0x02u         /*!<@brief Selects pin function 2 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO0_29 (coord B13), U24[13]/P0_29-ISP_FC0_RXD
  @{ */
#define BOARD_INITPINS_ISP_FC0_RXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ISP_FC0_RXD_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ISP_FC0_RXD_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_30 (coord A2), U24[12]/P0_30-ISP_FC0_TXD
  @{ */
#define BOARD_INITPINS_ISP_FC0_TXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ISP_FC0_TXD_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ISP_FC0_TXD_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO1_17 (coord N12), DebugLED_1
  @{ */
#define BOARD_INITPINS_DebugLED_1_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DebugLED_1_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DebugLED_1_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO1_18 (coord D1), J9[2]/P1_18-CAN1_RD
  @{ */
#define BOARD_INITPINS_FC8_SCL_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_FC8_SCL_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_FC8_SCL_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_ANAMODE_DI 0x40u    /*!<@brief Disable analog Mode */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC6 0x06u         /*!<@brief Selects pin function 6 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */

/*! @name PIO0_12 (coord M3), P1[2]/U22[4]/D5[5]/IF_SWDIO
  @{ */
#define PIN_SWD_DEBUG_IF_SWDIO_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PIN_SWD_DEBUG_IF_SWDIO_PIN 12U                   /*!<@brief PORT pin number */
#define PIN_SWD_DEBUG_IF_SWDIO_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_11 (coord L3), U16[4]/SWDCLK_TRGT
  @{ */
#define PIN_SWD_DEBUG_SWDCLK_TRGT_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PIN_SWD_DEBUG_SWDCLK_TRGT_PIN 11U                   /*!<@brief PORT pin number */
#define PIN_SWD_DEBUG_SWDCLK_TRGT_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO0_10 (coord P2), U16[12]/SWO_TRGT
  @{ */
#define PIN_SWD_DEBUG_SWO_TRGT_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PIN_SWD_DEBUG_SWO_TRGT_PIN 10U                   /*!<@brief PORT pin number */
#define PIN_SWD_DEBUG_SWO_TRGT_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_SWD_DEBUGPins(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_ANAMODE_DI 0x40u    /*!<@brief Disable analog Mode */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO1_7 (coord N1), PCIe2_PERST#
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_RST_2_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_RST_2_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_RST_2_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_RST_2_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_RST_2_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO3_25 (coord P9), PCIe1_PERST#
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_RST_1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_RST_1_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_RST_1_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_RST_1_PIN 25U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_RST_1_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO3_13 (coord H4), PCIe2_Power_swichting_3V3Aux
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PS_AUX_2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_AUX_2_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PS_AUX_2_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_AUX_2_PIN 13U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PS_AUX_2_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO2_7 (coord J2), PCIe1_Power_switching_3V3
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PS_3V3_1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_3V3_1_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PS_3V3_1_PORT 2U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_3V3_1_PIN 7U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PS_3V3_1_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO1_20 (coord M1), SUPP_1_Power_switching
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PS_12V_3_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_12V_3_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PS_12V_3_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_12V_3_PIN 20U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PS_12V_3_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO1_6 (coord G4), PCIe2_Power_switching_12V
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PS_12V_2_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_12V_2_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PS_12V_2_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_12V_2_PIN 6U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PS_12V_2_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO3_17 (coord K1), PCIe2_Power_switching_3V3
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PS_3V3_2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_3V3_2_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PS_3V3_2_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_3V3_2_PIN 17U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PS_3V3_2_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO4_4 (coord D9), PCIe1_Power_switching_12V
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PS_12V_1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_12V_1_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PS_12V_1_PORT 4U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_12V_1_PIN 4U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PS_12V_1_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO3_26 (coord K5), PCIe1_Power_switching_3V3Aux
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PS_AUX_1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_AUX_1_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PS_AUX_1_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_AUX_1_PIN 26U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PS_AUX_1_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO2_8 (coord F4), SUPP_2_Power_switching
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PS_12V_4_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_12V_4_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PS_12V_4_PORT 2U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PS_12V_4_PIN 8U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PS_12V_4_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PIO1_1 (coord K12), PCIe2_Plug_in_sensing
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PIS_2_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PIS_2_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PIS_2_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PIS_2_PIN 1U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PIS_2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO1_1 (coord K12), PCIe2_Plug_in_sensing
  @{ */
#define PIN_PCIE_FUNCTION_PIS_2_INT_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PIS_2_INT_PIN 1U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PIS_2_INT_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO1_0 (coord N3), PCIe1_Plug_in_sensing
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_PCIE_FUNCTION_PIS_1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PIN_PCIE_FUNCTION_PIS_1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define PIN_PCIE_FUNCTION_PIS_1_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PIS_1_PIN 0U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PIS_1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO1_0 (coord N3), PCIe1_Plug_in_sensing
  @{ */
#define PIN_PCIE_FUNCTION_PIS_1_INT_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PIN_PCIE_FUNCTION_PIS_1_INT_PIN 0U                   /*!<@brief PORT pin number */
#define PIN_PCIE_FUNCTION_PIS_1_INT_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_PCIeFunctionPins(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO1_17 (coord N12), DebugLED_1
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_USRLED_DebugLED_1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_USRLED_DebugLED_1_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define PIN_USRLED_DebugLED_1_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PIN_USRLED_DebugLED_1_PIN 17U                   /*!<@brief PORT pin number */
#define PIN_USRLED_DebugLED_1_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO2_19 (coord P12), DebugLED_2
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_USRLED_DebugLED_2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_USRLED_DebugLED_2_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define PIN_USRLED_DebugLED_2_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PIN_USRLED_DebugLED_2_PIN 19U                   /*!<@brief PORT pin number */
#define PIN_USRLED_DebugLED_2_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO3_27 (coord P14), DebugLED_0
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_USRLED_DebugLED_0_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_USRLED_DebugLED_0_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */
#define PIN_USRLED_DebugLED_0_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_USRLED_DebugLED_0_PIN 27U                   /*!<@brief PORT pin number */
#define PIN_USRLED_DebugLED_0_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_LEDs(void); /* Function assigned for the Cortex-M4F */

#define PIO220_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO220_FUNC_ALT3 0x03u        /*!<@brief Selects pin function.: Alternative connection 3. */

/*! @name PIO2_20 (coord P13), PMBus
  @{ */
#define PIN_UARTPMBus_SCL_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PIN_UARTPMBus_SCL_PIN 20U                   /*!<@brief PORT pin number */
#define PIN_UARTPMBus_SCL_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_DEBUG_UARTPins(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_ANALOG_EN 0x00u     /*!<@brief Enables analog function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*!
 * @brief This is a de-initialization function for 'PIN_INIT_DEBUG_UARTPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void PIN_INIT_DEBUG_UARTPins_deinit(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_FUNC7 0x07u         /*!<@brief Selects pin function 7 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO4_8 (coord B14), U12[17]/JP11[1]/P4_8-ENET_TXD0
  @{ */
#define PIN_ENET_ENET_TXD0_PORT 4U                  /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_TXD0_PIN 8U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_TXD0_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO0_17 (coord E14), U12[18]/P0_17-ENET_TXD1
  @{ */
#define PIN_ENET_ENET_TXD1_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_TXD1_PIN 17U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_TXD1_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO4_13 (coord B6), U12[16]/P4_13-ENET_TX_EN
  @{ */
#define PIN_ENET_ENET_TX_EN_PORT 4U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_TX_EN_PIN 13U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_TX_EN_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO4_11 (coord A9), U12[8]/JP12[1]/J3[4]/JP12[3]/P4_11-USB0_ID/P4_11-ENET_RXD0
  @{ */
#define PIN_ENET_ENET_RXD0_PORT 4U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_RXD0_PIN 11U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_RXD0_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO4_12 (coord A6), U12[7]/P4_12-ENET_RXD1
  @{ */
#define PIN_ENET_ENET_RXD1_PORT 4U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_RXD1_PIN 12U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_RXD1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO4_10 (coord B9), U12[11]/P4_10-ENET_CRS_DV
  @{ */
#define PIN_ENET_ENET_CRS_DV_PORT 4U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_CRS_DV_PIN 10U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_CRS_DV_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO4_16 (coord C4), U12[12]/P4_16-ENET_MDIO
  @{ */
#define PIN_ENET_ENET_MDIO_PORT 4U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_MDIO_PIN 16U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_MDIO_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO4_15 (coord A4), U12[13]/P4_15-ENET_MDC
  @{ */
#define PIN_ENET_ENET_MDC_PORT 4U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_MDC_PIN 15U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_MDC_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO2_26 (coord H11), U12[15]/P2_26-ENET_PHY_RSTn
  @{ */

/* Symbols to be used with GPIO driver */
#define PIN_ENET_ENET_PHY_RSTn_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PIN_ENET_ENET_PHY_RSTn_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define PIN_ENET_ENET_PHY_RSTn_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_PHY_RSTn_PIN 26U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_PHY_RSTn_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO4_14 (coord B5), JS18[2]/P4_14-ENET_RX_CLK
  @{ */
#define PIN_ENET_ENET_RX_CLK_PORT 4U                   /*!<@brief PORT peripheral base pointer */
#define PIN_ENET_ENET_RX_CLK_PIN 14U                   /*!<@brief PORT pin number */
#define PIN_ENET_ENET_RX_CLK_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_ENETPins(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_ANALOG_EN 0x00u     /*!<@brief Enables analog function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*!
 * @brief This is a de-initialization function for 'PIN_INIT_ENETPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void PIN_INIT_ENETPins_deinit(void); /* Function assigned for the Cortex-M4F */

/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO013_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO013_FUNC_ALT1 0x01u
/*!
 * @brief Controls slew rate of I2C pad.: I2C mode. */
#define PIO013_I2CSLEW_I2C_MODE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO014_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO014_FUNC_ALT1 0x01u
/*!
 * @brief Controls slew rate of I2C pad.: I2C mode. */
#define PIO014_I2CSLEW_I2C_MODE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO122_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO122_FUNC_ALT1 0x01u
/*!
 * @brief Controls open-drain mode.: Normal. Normal push-pull output */
#define PIO122_OD_NORMAL 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO122_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO217_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO217_FUNC_ALT5 0x05u
/*!
 * @brief Controls open-drain mode.: Normal. Normal push-pull output */
#define PIO217_OD_NORMAL 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO217_SLEW_FAST 0x01u
/*!
 * @brief Enables or disables analog mode.: Disable analog Mode. */
#define PIO321_ANAMODE_DISABLED 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO321_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Controls input glitch filter.: Filter enabled. Noise pulses below approximately 10 ns are filtered out. */
#define PIO321_FILTEROFF_ENABLED 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO321_FUNC_ALT1 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO321_MODE_INACTIVE 0x00u
/*!
 * @brief Enables or disables analog mode.: Disable analog Mode. */
#define PIO322_ANAMODE_DISABLED 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO322_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Controls input glitch filter.: Filter enabled. Noise pulses below approximately 10 ns are filtered out. */
#define PIO322_FILTEROFF_ENABLED 0x00u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO322_FUNC_ALT1 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO322_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO323_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO323_FUNC_ALT1 0x01u
/*!
 * @brief Controls slew rate of I2C pad.: I2C mode. */
#define PIO323_I2CSLEW_I2C_MODE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO324_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO324_FUNC_ALT1 0x01u
/*!
 * @brief Controls slew rate of I2C pad.: I2C mode. */
#define PIO324_I2CSLEW_I2C_MODE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO42_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO42_FUNC_ALT2 0x02u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO42_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO43_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO43_FUNC_ALT2 0x02u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO43_SLEW_FAST 0x01u

/*! @name PIO1_22 (coord P11), I2C_SUPP_SCL
  @{ */
#define PIN_I2C_SUPP_SCL_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_SUPP_SCL_PIN 22U                   /*!<@brief PORT pin number */
#define PIN_I2C_SUPP_SCL_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO2_17 (coord P10), I2C_SUPP_SDA
  @{ */
#define PIN_I2C_SUPP_SDA_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_SUPP_SDA_PIN 17U                   /*!<@brief PORT pin number */
#define PIN_I2C_SUPP_SDA_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO0_13 (coord F11), PCIe2_PowerMeasurement_I2C_SDA
  @{ */
#define PIN_I2C_SMB1_SDA_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_SMB1_SDA_PIN 13U                   /*!<@brief PORT pin number */
#define PIN_I2C_SMB1_SDA_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO0_14 (coord E13), PCIe2_PowerMeasurement_I2C_SCL
  @{ */
#define PIN_I2C_SMB1_SCL_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_SMB1_SCL_PIN 14U                   /*!<@brief PORT pin number */
#define PIN_I2C_SMB1_SCL_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO3_24 (coord E2), PCIe1_PowerMeasurement_I2C_SCL
  @{ */
#define PIN_I2C_SMB2_SCL_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_SMB2_SCL_PIN 24U                   /*!<@brief PORT pin number */
#define PIN_I2C_SMB2_SCL_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO3_23 (coord C2), PCIe1_PowerMeasurement_I2C_SDA
  @{ */
#define PIN_I2C_SMB2_SDA_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_SMB2_SDA_PIN 23U                   /*!<@brief PORT pin number */
#define PIN_I2C_SMB2_SDA_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO4_2 (coord F14), PCIe1_PowerMeasurement_I2C_SDA
  @{ */
#define PIN_I2C_PM1_SDA_PORT 4U                  /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_PM1_SDA_PIN 2U                   /*!<@brief PORT pin number */
#define PIN_I2C_PM1_SDA_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO4_3 (coord F13), PCIe1_PowerMeasurement_I2C_SCL
  @{ */
#define PIN_I2C_PM1_SCL_PORT 4U                  /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_PM1_SCL_PIN 3U                   /*!<@brief PORT pin number */
#define PIN_I2C_PM1_SCL_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PIO3_22 (coord N5), PCIe2_PowerMeasurement_I2C_SCL
  @{ */
#define PIN_I2C_PM2_SCL_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_PM2_SCL_PIN 22U                   /*!<@brief PORT pin number */
#define PIN_I2C_PM2_SCL_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PIO3_21 (coord P5), PCIe2_PowerMeasurement_I2C_SDA
  @{ */
#define PIN_I2C_PM2_SDA_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_PM2_SDA_PIN 21U                   /*!<@brief PORT pin number */
#define PIN_I2C_PM2_SDA_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_I2Cpins(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_ANAMODE_DI 0x40u    /*!<@brief Disable analog Mode */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_FUNC3 0x03u         /*!<@brief Selects pin function 3 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO3_20 (coord N2), JTAG_CLK
  @{ */
#define PINS_JTAG_JTAG_TCK_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PINS_JTAG_JTAG_TCK_PIN 20U                   /*!<@brief PORT pin number */
#define PINS_JTAG_JTAG_TCK_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO2_13 (coord P7), PCIe1_JTAG_TDO
  @{ */

/* Symbols to be used with GPIO driver */
#define PINS_JTAG_JTAG_TDO_1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINS_JTAG_JTAG_TDO_1_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define PINS_JTAG_JTAG_TDO_1_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PINS_JTAG_JTAG_TDO_1_PIN 13U                   /*!<@brief PORT pin number */
#define PINS_JTAG_JTAG_TDO_1_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO2_1 (coord P4), JTAG_TMS
  @{ */

/* Symbols to be used with GPIO driver */
#define PINS_JTAG_JTAG_TMS_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINS_JTAG_JTAG_TMS_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define PINS_JTAG_JTAG_TMS_PORT 2U                  /*!<@brief PORT peripheral base pointer */
#define PINS_JTAG_JTAG_TMS_PIN 1U                   /*!<@brief PORT pin number */
#define PINS_JTAG_JTAG_TMS_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO2_10 (coord P1), PCIe2_JTAG_TDO
  @{ */

/* Symbols to be used with GPIO driver */
#define PINS_JTAG_JTAG_TDO_2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINS_JTAG_JTAG_TDO_2_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */
#define PINS_JTAG_JTAG_TDO_2_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PINS_JTAG_JTAG_TDO_2_PIN 10U                   /*!<@brief PORT pin number */
#define PINS_JTAG_JTAG_TDO_2_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO2_0 (coord P3), PCIe2_JTAG_TDI
  @{ */

/* Symbols to be used with GPIO driver */
#define PINS_JTAG_JTAG_TDI_2_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINS_JTAG_JTAG_TDI_2_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define PINS_JTAG_JTAG_TDI_2_PORT 2U                  /*!<@brief PORT peripheral base pointer */
#define PINS_JTAG_JTAG_TDI_2_PIN 0U                   /*!<@brief PORT pin number */
#define PINS_JTAG_JTAG_TDI_2_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO1_8 (coord P8), PCIe1_JTAG_TDI
  @{ */

/* Symbols to be used with GPIO driver */
#define PINS_JTAG_JTAG_TDI_1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINS_JTAG_JTAG_TDI_1_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */
#define PINS_JTAG_JTAG_TDI_1_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PINS_JTAG_JTAG_TDI_1_PIN 8U                   /*!<@brief PORT pin number */
#define PINS_JTAG_JTAG_TDI_1_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_PcieJTAGPins(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_ANALOG_EN 0x00u     /*!<@brief Enables analog function */
#define IOCON_PIO_ANAMODE_DI 0x40u    /*!<@brief Disable analog Mode */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*!
 * @brief This is a de-initialization function for 'PIN_INIT_PcieJTAGPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void PIN_INIT_PcieJTAGPins_deinit(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO2_2 (coord C3), J9[6]/LED3/P2_2-CT1MAT1-USR_LED3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_PIN_LED3_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_PIN_LED3_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define BOARD_PIN_LED3_PORT 2U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_PIN_LED3_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_PIN_LED3_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO3_3 (coord A13), J9[8]/LED2/P3_3-USR_LED2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_PIN_LED2_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_PIN_LED2_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */
#define BOARD_PIN_LED2_PORT 3U                  /*!<@brief PORT peripheral base pointer */
#define BOARD_PIN_LED2_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_PIN_LED2_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PIO3_14 (coord E3), J13[5]/LED1/P3_14-CT3MAT1-USR_LED1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_PIN_LED1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_PIN_LED1_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_PIN_LED1_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_PIN_LED1_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_PIN_LED1_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_PIN_INIT_LED(void); /* Function assigned for the Cortex-M4F */

#define PIO218_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO218_FUNC_ALT2 0x02u        /*!<@brief Selects pin function.: Alternative connection 2. */
#define PIO220_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO220_FUNC_ALT2 0x02u        /*!<@brief Selects pin function.: Alternative connection 2. */

/*! @name PIO2_20 (coord P13), PMBus
  @{ */
#define PIN_PMBUS_PMBus_SCL_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PIN_PMBUS_PMBus_SCL_PIN 20U                   /*!<@brief PORT pin number */
#define PIN_PMBUS_PMBus_SCL_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO2_18 (coord N10), PMBus
  @{ */
#define PIN_PMBUS_PMBus_SDA_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PIN_PMBUS_PMBus_SDA_PIN 18U                   /*!<@brief PORT pin number */
#define PIN_PMBUS_PMBus_SDA_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_PMBUS(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_ANALOG_EN 0x00u     /*!<@brief Enables analog function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*!
 * @brief This is a de-initialization function for 'PIN_INIT_PMBUS' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void PIN_INIT_PMBUS_deinit(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_INPFILT_OFF 0x0200u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO0_29 (coord B13), U24[13]/P0_29-ISP_FC0_RXD
  @{ */
#define BOARD_PIN_ISP_FC0_RXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_PIN_ISP_FC0_RXD_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_PIN_ISP_FC0_RXD_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_30 (coord A2), U24[12]/P0_30-ISP_FC0_TXD
  @{ */
#define BOARD_PIN_ISP_FC0_TXD_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_PIN_ISP_FC0_TXD_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_PIN_ISP_FC0_TXD_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_PIN_INIT_DEBUGConsole(void); /* Function assigned for the Cortex-M4F */

/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO013_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO013_FUNC_ALT1 0x01u
/*!
 * @brief
 * Controls the current sink capability of the pin.
 * : High drive.
 * Output drive sink is 20 mA.
 * This is needed for Fast Mode Plus I 2C.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO013_I2CDRIVE_HIGH 0x01u
/*!
 * @brief Controls slew rate of I2C pad.: I2C mode. */
#define PIO013_I2CSLEW_I2C_MODE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO014_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO014_FUNC_ALT1 0x01u
/*!
 * @brief
 * Controls the current sink capability of the pin.
 * : High drive.
 * Output drive sink is 20 mA.
 * This is needed for Fast Mode Plus I 2C.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO014_I2CDRIVE_HIGH 0x01u
/*!
 * @brief Controls slew rate of I2C pad.: I2C mode. */
#define PIO014_I2CSLEW_I2C_MODE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO323_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO323_FUNC_ALT1 0x01u
/*!
 * @brief
 * Controls the current sink capability of the pin.
 * : High drive.
 * Output drive sink is 20 mA.
 * This is needed for Fast Mode Plus I 2C.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO323_I2CDRIVE_HIGH 0x01u
/*!
 * @brief Controls slew rate of I2C pad.: I2C mode. */
#define PIO323_I2CSLEW_I2C_MODE 0x00u
/*!
 * @brief Input polarity.: Disabled. Input function is not inverted. */
#define PIO323_INVERT_DISABLED 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO324_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO324_FUNC_ALT1 0x01u
/*!
 * @brief
 * Controls the current sink capability of the pin.
 * : High drive.
 * Output drive sink is 20 mA.
 * This is needed for Fast Mode Plus I 2C.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO324_I2CDRIVE_HIGH 0x01u
/*!
 * @brief Controls slew rate of I2C pad.: I2C mode. */
#define PIO324_I2CSLEW_I2C_MODE 0x00u

/*! @name PIO0_13 (coord F11), PCIe2_PowerMeasurement_I2C_SDA
  @{ */
#define PIN_I2C_PM2_SDA_HS_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_PM2_SDA_HS_PIN 13U                   /*!<@brief PORT pin number */
#define PIN_I2C_PM2_SDA_HS_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_14 (coord E13), PCIe2_PowerMeasurement_I2C_SCL
  @{ */
#define PIN_I2C_PM2_SCL_HS_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_PM2_SCL_HS_PIN 14U                   /*!<@brief PORT pin number */
#define PIN_I2C_PM2_SCL_HS_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO3_24 (coord E2), PCIe1_PowerMeasurement_I2C_SCL
  @{ */
#define PIN_I2C_PM1_SCL_HS_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_PM1_SCL_HS_PIN 24U                   /*!<@brief PORT pin number */
#define PIN_I2C_PM1_SCL_HS_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO3_23 (coord C2), PCIe1_PowerMeasurement_I2C_SDA
  @{ */
#define PIN_I2C_PM1_SDA_HS_PORT 3U                   /*!<@brief PORT peripheral base pointer */
#define PIN_I2C_PM1_SDA_HS_PIN 23U                   /*!<@brief PORT pin number */
#define PIN_I2C_PM1_SDA_HS_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PIN_INIT_I2Cpins_HS(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
