#! /bin/bash
# shellcheck source=/dev/null
source config.sh

a_1=$1 
a_2=$2 
a_3=$3 

if [ "$a_1" == "Board1" ]
then
    a_1="$Board_MAC_1"
   echo "$a_1"
elif [ "$a_1" == "Board2" ]
then
    a_1="$Board_MAC_2"
   echo "$a_1"
fi

if [ "$a_2" == "-ON" ]
then
    echo "${a_1}:ON"
    mosquitto_pub -h "${Broker_IP}" -t "${pre_Topic}/$a_1/ON_OFF" -m "ON"
fi

if [ "$a_1" == "-t" ]
then 
        mosquitto_pub -h "${Broker_IP}" -t "Config/$Board_MAC_1/Time" -m "$(date +%s)"
  	mosquitto_pub -h "${Broker_IP}" -t "Config/$Board_MAC_2/Time" -m "$(date +%s)"
fi

#monitor
if [ "$a_1" == "-m" ]
then
    gnome-terminal --title="${Board_MAC_1}-PCIe1-$Board_1_DUT_Name_1" -- mosquitto_sub -h "${Broker_IP}" -t "${pre_Topic}/$Board_1_DUT_Name_1/#" -F %X
    gnome-terminal --title="${Board_MAC_1}-PCIe2-$Board_1_DUT_Name_2" -- mosquitto_sub -h "${Broker_IP}" -t "${pre_Topic}/$Board_1_DUT_Name_2/#" -F %X
    gnome-terminal --title="${Board_MAC_2}-PCIe1-$Board_2_DUT_Name_1" -- mosquitto_sub -h "${Broker_IP}" -t "${pre_Topic}/$Board_2_DUT_Name_1/#" -F %X
    gnome-terminal --title="${Board_MAC_2}-PCIe2-$Board_2_DUT_Name_2" -- mosquitto_sub -h "${Broker_IP}" -t "${pre_Topic}/$Board_2_DUT_Name_2/#" -F %X
    gnome-terminal --title="Config" -- mosquitto_sub -h "${Broker_IP}" -t "Config/#" 
fi


#update names
if [ "$a_1" == "-un" ]
then
    echo "update names"
    mosquitto_pub -h "${Broker_IP}" -r -t "Config/$Board_MAC_1/PCIe1_DUT_Name" -m "$Board_1_DUT_Name_1"
    mosquitto_pub -h "${Broker_IP}" -r -t "Config/$Board_MAC_1/PCIe2_DUT_Name" -m "$Board_1_DUT_Name_2"
    mosquitto_pub -h "${Broker_IP}" -r -t "Config/$Board_MAC_2/PCIe1_DUT_Name" -m "$Board_2_DUT_Name_1"
    mosquitto_pub -h "${Broker_IP}" -r -t "Config/$Board_MAC_2/PCIe2_DUT_Name" -m "$Board_2_DUT_Name_2"
    # if [ "$a_1" == "$Board_1_DUT_Name_1" ]
    # then
    #   mac=$Board_1_DUT_Name_1
    # elif [ "$a_1" == "$Board_1_DUT_Name_2" ]
    # then
    #   mac=$Board_1_DUT_Name_2
    # fi
    #  mosquitto_pub -h localhost  -r -t "Config/$mac/PCIe${3}_DUT_Name" -m ""
fi

if [ "$a_2" == "-reset" ]
then
    echo "reset: $a_1"
    mosquitto_pub -h "${Broker_IP}" -t "Config/${a_1}/Reset" -m "reset"
fi
#set frequency
if [ "$a_2" == "-f" ]
then 
    mosquitto_pub -h "${Broker_IP}" -t "Config/${a_1}/Frequency" -m "${a_3}"
fi





if [ "$a_1" == "-help" ]
    then
    echo "naa_measurement {MAC Address} [option]"
    echo "-un     update DUT names, have to bet set in config.sh"
    echo "-reset {mac-Address} -reset trigger a board reset of the µC"
    echo "-m monitor, opens a bunch of terminals to show the measurement data on the broker and the config topic "
    echo "-f sets the frequency"
fi
