.TH "Measurement/INA226_driver Directory Reference" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Measurement/INA226_driver Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBina226\&.c\fP"
.br
.ti -1c
.RI "file \fBina226\&.h\fP"
.br
.ti -1c
.RI "file \fBina226_measurement_frequency_adjusting\&.c\fP"
.br
.ti -1c
.RI "file \fBina226_measurement_frequency_adjusting\&.h\fP"
.br
.in -1c
