.TH "Controller/control_task.c" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller/control_task.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'Controller/control_task\&.h'\fP
.br
\fC#include 'Config/pms_control_commands\&.h'\fP
.br
\fC#include 'Measurement/pms_HardwareCheck\&.h'\fP
.br
\fC#include 'mqtt\&.h'\fP
.br
\fC#include 'Ethernet/pms_mqtt_wrapper\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for NAA-Measurement-Carrier-System from the source code\&.
