.TH "control_parameters_t" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
control_parameters_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <control_task\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBmeasurement_active\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool control_parameters_t::measurement_active"


.SH "Author"
.PP 
Generated automatically by Doxygen for NAA-Measurement-Carrier-System from the source code\&.
