.TH "ina226_frequency_t" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ina226_frequency_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ina226_measurement_frequency_adjusting\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBfrequency\fP"
.br
.ti -1c
.RI "\fBina226_config_data_t\fP \fBconfig\fP"
.br
.ti -1c
.RI "\fBINA226_VBUSCT_t\fP \fBvbusct\fP"
.br
.ti -1c
.RI "\fBINA226_VSHCT_t\fP \fBvshct\fP"
.br
.ti -1c
.RI "\fBINA226_NoA_t\fP \fBnoa\fP"
.br
.ti -1c
.RI "int \fBremainder\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBina226_config_data_t\fP ina226_frequency_t::config"

.SS "float ina226_frequency_t::frequency"

.SS "\fBINA226_NoA_t\fP ina226_frequency_t::noa"

.SS "int ina226_frequency_t::remainder"

.SS "\fBINA226_VBUSCT_t\fP ina226_frequency_t::vbusct"

.SS "\fBINA226_VSHCT_t\fP ina226_frequency_t::vshct"


.SH "Author"
.PP 
Generated automatically by Doxygen for NAA-Measurement-Carrier-System from the source code\&.
