.TH "PCIe_Imax" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCIe_Imax \- PCIe Maximaler Strom
.PP
 \- Maximaler Strom auf den zu messenden Leitungen, resultierend aus Leistung und Spannung\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIMAX_PCIE_SLOT_12V\fP   5\&.5"
.br
.ti -1c
.RI "#define \fBIMAX_PCIE_SLOT_3V3\fP   3"
.br
.ti -1c
.RI "#define \fBIMAX_PCIE_SUPP\fP   12\&.5"
.br
.in -1c
.SH "Detailed Description"
.PP 
Maximaler Strom auf den zu messenden Leitungen, resultierend aus Leistung und Spannung\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define IMAX_PCIE_SLOT_12V   5\&.5"
in A 
.SS "#define IMAX_PCIE_SLOT_3V3   3"
in A 
.SS "#define IMAX_PCIE_SUPP   12\&.5"
in A 
.SH "Author"
.PP 
Generated automatically by Doxygen for NAA-Measurement-Carrier-System from the source code\&.
