.TH "Measurement/I2C/pms_i2c_callbacks.h" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Measurement/I2C/pms_i2c_callbacks.h
.SH SYNOPSIS
.br
.PP
\fC#include 'fsl_i2c\&.h'\fP
.br
\fC#include 'fsl_i2c_freertos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBI2C_PCIE_clb\fP (I2C_Type *base, i2c_master_handle_t *handle, status_t completionStatus, void *userData)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void I2C_PCIE_clb (I2C_Type * base, i2c_master_handle_t * handle, status_t completionStatus, void * userData)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NAA-Measurement-Carrier-System from the source code\&.
