.TH "Config/pms_control_commands.h" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config/pms_control_commands.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_TOPIC\fP   'Config'"
.br
.ti -1c
.RI "#define \fBPRE_TOPIC\fP   'devices'"
.br
.ti -1c
.RI "#define \fBLOG_TOPIC\fP   'Log'"
.br
.ti -1c
.RI "#define \fBUSE_CASE_COMMAND\fP   'UseCase'"
.br
.ti -1c
.RI "#define \fBRESET_COMMAND\fP   'Reset'"
.br
.ti -1c
.RI "#define \fBFREQUENCY_TOPIC\fP   'Frequency'"
.br
.ti -1c
.RI "#define \fBPCIE1_TOPIC\fP   'PCIe1_DUT_Name'"
.br
.ti -1c
.RI "#define \fBPCIE2_TOPIC\fP   'PCIe2_DUT_Name'"
.br
.ti -1c
.RI "#define \fBTIME_TOPIC\fP   'Time'"
.br
.ti -1c
.RI "#define \fBON_OFF_COMMAND\fP   'ON_OFF'"
.br
.ti -1c
.RI "#define \fBMEAUSREMENT_DATA_TOPIC\fP   'Data'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONFIG_TOPIC   'Config'"
Configuration topics 
.SS "#define FREQUENCY_TOPIC   'Frequency'"

.SS "#define LOG_TOPIC   'Log'"
Sub topics 
.SS "#define MEAUSREMENT_DATA_TOPIC   'Data'"

.SS "#define ON_OFF_COMMAND   'ON_OFF'"
DUT Topics 
.SS "#define PCIE1_TOPIC   'PCIe1_DUT_Name'"

.SS "#define PCIE2_TOPIC   'PCIe2_DUT_Name'"

.SS "#define PRE_TOPIC   'devices'"

.SS "#define RESET_COMMAND   'Reset'"

.SS "#define TIME_TOPIC   'Time'"

.SS "#define USE_CASE_COMMAND   'UseCase'"

.SH "Author"
.PP 
Generated automatically by Doxygen for NAA-Measurement-Carrier-System from the source code\&.
