.TH "Ethernet/pms_byte_swap.c" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ethernet/pms_byte_swap.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint16_t \fBswap_uint16\fP (uint16_t val)"
.br
.RI "Byte swap unsigned short\&. "
.ti -1c
.RI "int16_t \fBswap_int16\fP (int16_t val)"
.br
.RI "Byte swap short\&. "
.ti -1c
.RI "void \fBswap_uint32\fP (uint32_t *val)"
.br
.RI "Byte swap unsigned int\&. "
.ti -1c
.RI "int32_t \fBswap_int32\fP (int32_t val)"
.br
.RI "Byte swap int\&. "
.ti -1c
.RI "int64_t \fBswap_int64\fP (int64_t val)"
.br
.ti -1c
.RI "uint64_t \fBswap_uint64\fP (uint64_t val)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int16_t swap_int16 (int16_t val)"

.PP
Byte swap short\&. 
.SS "int32_t swap_int32 (int32_t val)"

.PP
Byte swap int\&. 
.SS "int64_t swap_int64 (int64_t val)"

.SS "uint16_t swap_uint16 (uint16_t val)"

.PP
Byte swap unsigned short\&. 
.SS "void swap_uint32 (uint32_t * val)"

.PP
Byte swap unsigned int\&. 
.SS "uint64_t swap_uint64 (uint64_t val)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NAA-Measurement-Carrier-System from the source code\&.
