.TH "Ethernet/pms_ethernet.c" 3 "Wed Apr 3 2024" "NAA-Measurement-Carrier-System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ethernet/pms_ethernet.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Config/pms_config\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Paul Mamatis 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
Jun 14, 2023
.RE
.PP
.SH "TODO"
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NAA-Measurement-Carrier-System from the source code\&.
